import { existsSync } from 'node:fs';
import { cp, mkdir, mkdtemp, readdir, rm, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { git, isGitRepo, messageOf } from '@mulligan/core';
import { safeRelativePath, type ProposedChange } from './change.js';

/**
 * An isolated copy of the project for one candidate: a temporary git
 * worktree carrying the developer's uncommitted work. Candidates are applied
 * and verified here; the developer's own working tree is never touched.
 * Mulligan manages these worktrees itself and removes them afterwards.
 */
export interface Sandbox {
  dir: string;
  cleanup(): Promise<void>;
}

export class SandboxUnavailable extends Error {
  override name = 'SandboxUnavailable';
}

async function linkDependencies(root: string, dir: string): Promise<void> {
  // Link node_modules (root and one or two levels down, for workspaces) so checks can run without reinstalling.
  async function visit(rel: string, depth: number): Promise<void> {
    const abs = path.join(root, rel);
    let entries;
    try {
      entries = await readdir(abs, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (!e.isDirectory() || e.name === '.git' || e.name === '.mulligan') continue;
      const childRel = path.join(rel, e.name);
      if (e.name === 'node_modules') {
        const target = path.join(dir, childRel);
        if (!existsSync(target) && existsSync(path.dirname(target))) {
          await symlink(path.join(root, childRel), target, 'junction').catch(() => undefined);
        }
      } else if (depth < 2) {
        await visit(childRel, depth + 1);
      }
    }
  }
  await visit('', 0);
}

export async function createSandbox(root: string): Promise<Sandbox> {
  if (!(await isGitRepo(root))) throw new SandboxUnavailable('Not a git repository — candidates cannot be verified in isolation.');
  try {
    await git(root, ['rev-parse', '--verify', 'HEAD']);
  } catch {
    throw new SandboxUnavailable('The repository has no commits yet — candidates cannot be verified in isolation.');
  }
  const parent = await mkdtemp(path.join(os.tmpdir(), 'mulligan-cand-'));
  const dir = path.join(parent, 'wt');
  await git(root, ['worktree', 'add', '--detach', dir, 'HEAD']);
  const cleanup = async (): Promise<void> => {
    await git(root, ['worktree', 'remove', '--force', dir]).catch(() => undefined);
    await rm(parent, { recursive: true, force: true }).catch(() => undefined);
    await git(root, ['worktree', 'prune']).catch(() => undefined);
  };
  try {
    // Carry the developer's uncommitted changes and untracked files.
    const wip = await git(root, ['diff', 'HEAD', '--binary']);
    if (wip.trim()) {
      const patch = path.join(parent, 'wip.patch');
      await writeFile(patch, wip, 'utf8');
      await git(dir, ['apply', '--whitespace=nowarn', patch]);
    }
    const untracked = (await git(root, ['ls-files', '--others', '--exclude-standard']))
      .split(/\r?\n/)
      .filter((f) => f && !f.startsWith('.mulligan/') && f !== '.MulliganMem');
    for (const f of untracked) {
      await mkdir(path.dirname(path.join(dir, f)), { recursive: true });
      await cp(path.join(root, f), path.join(dir, f)).catch(() => undefined);
    }
    // The index becomes the baseline; the candidate's diff is measured against it.
    await git(dir, ['add', '-A']);
    await linkDependencies(root, dir);
  } catch (error) {
    await cleanup();
    throw error;
  }
  return { dir, cleanup };
}

export interface ApplyResult {
  applied: boolean;
  error?: string;
  /** The real diff, generated by git, relative to the developer's working tree. */
  diff: string;
}

export async function applyToSandbox(sandbox: Sandbox, change: ProposedChange): Promise<ApplyResult> {
  try {
    if (change.files.length > 0) {
      for (const f of change.files) {
        const rel = safeRelativePath(sandbox.dir, f.path);
        if (!rel) return { applied: false, error: `refused path outside the project: ${f.path}`, diff: '' };
        const target = path.join(sandbox.dir, rel);
        await mkdir(path.dirname(target), { recursive: true });
        await writeFile(target, f.content, 'utf8');
      }
    } else if (change.diff) {
      const patch = path.join(path.dirname(sandbox.dir), 'candidate.patch');
      await writeFile(patch, change.diff, 'utf8');
      await git(sandbox.dir, ['apply', '--recount', '--whitespace=nowarn', patch]);
    } else {
      return { applied: false, error: 'the candidate proposed no file changes', diff: '' };
    }
    await git(sandbox.dir, ['add', '-N', '.']);
    const diff = await git(sandbox.dir, ['diff', '--binary']);
    if (!diff.trim()) return { applied: false, error: 'the candidate changed nothing', diff: '' };
    return { applied: true, diff };
  } catch (error) {
    return { applied: false, error: messageOf(error).split('\n').slice(0, 3).join(' '), diff: '' };
  }
}
